# CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps.py --config config_template.yaml
--- 
exp_arguments:
  # number of classes
  n_classes: 2
  # name tag for saving generated figures and assets #/data02/gkim/stem_cell_jwshin/HEATMAP_OUTPUT 
  save_exp_code: HMAP_OUTPUT
  # where to save raw asset files #/data02/gkim/stem_cell_jwshin/heatmaps/heatmap_raw_results 
  raw_save_dir: hmaps2/hmap_raw_results
  # where to save final heatmaps #/data02/gkim/stem_cell_jwshin/heatmaps/heatmap_production_results 
  production_save_dir: hmaps2/hmap_prod_results
  batch_size: 32
data_arguments: 
  # where is data stored; can be a single str path or a dictionary of key, data_dir mapping
  data_dir: /data02/gkim/stem_cell_jwshin/data/23_SEC1H5_wider_v3_allh_onRA/ 
  # heatmaps/demo/slides/
  # column name for key in data_dir (if a dict mapping is used)
  data_dir_key: source
  # csv list containing slide_ids (can additionally have seg/patch paramters, class labels, etc.)
  process_list: null
  #heatmap_demo_dataset.csv
  # preset file for segmentation/patching
  preset: null
  #presets/bwh_biopsy.csv
  # file extention for slides
  slide_ext: .h5
  # .svs
  # label dictionary for str: interger mapping (optional)
  label_dict:
    good_psc: 0
    bad_psc: 1                        
patching_arguments:
  # arguments for patching
  patch_size: 384
  overlap: 0.875 #0.5
  patch_level: 0
  custom_downsample: 1
encoder_arguments:
  # arguments for the pretrained encoder model 
  model_name: resnet50_trunc
  # currently support: resnet50_trunc, uni_v1, conch_v1 (useless for gkim impmentation which is fixed for ae)
  target_img_size: 384
  # resize images to this size before feeding to encoder
model_arguments: 
  # arguments for initializing model from checkpoint
  ckpt_path: /data02/gkim/stem_cell_jwshin/src/python/CLAM_gkim/results/task_3_good_psc_vs_bad_psc_CLAM_50_s1/s_0_checkpoint.pt
  #heatmaps/demo/ckpts/s_0_checkpoint.pt
  model_type: clam_sb
  # see utils/eval_utils/
  initiate_fn: initiate_model
  # see utils/eval_utils/
  model_size: gkim
  drop_out: 0.25
  # drop_out value of 0.0 skips the creation of a dropout layer and causes failure in 
  embed_dim: 4096
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: 0
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.4
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # whether to calculate percentile scores in reference to the set of non-overlapping patches
  use_ref_scores: true
  # whether to use gaussian blur for further smoothing
  blur: false
  # whether to shift the 4 default corner points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false 
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  calc_heatmap: true
  # whether to binarize attention scores
  binarize: false
  # binarization threshold: (0, 1)
  binary_thresh: -1
  # factor for downscaling the heatmap before final dispaly
  custom_downsample: 1
  cmap: jet
sample_arguments:
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 9 # save top-k patches 
      # was 15 but fixed by gkim in case of small colonies
      mode: topk