close all
clear
clc
dir_ref = '/data01/gkim/stem_cell_jwshin/data/231229_SEC1PNG_wider_v3';
%'/data02/gkim/stem_cell_jwshin/data/230306_MIPH5_wider_v2';
dir_data = '/data01/gkim/stem_cell_jwshin/data/231229_MIPH5_wider_v3';

if ~exist(dir_ref)
    error('no dir_ref')
end

cd(dir_data)
cd('00_train')

list_cls = dir('*_*');

for iter_cls = 1:length(list_cls)
    
    cd(dir_data)
    cd('00_train')
    cd(list_cls(iter_cls).name)

    list_h5 = dir('*.h5');
    if length(list_h5) == 0
        list_h5 = dir('*.mat');
    end

    for iter_h5 = 1:length(list_h5)
    
        if exist([dir_ref '/00_train_bad/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name])

            mkdir([dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

            movefile([dir_data '/00_train/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name],...
                [dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

        elseif exist([dir_ref '/00_train_bad/' ...
                list_cls(iter_cls).name '/'...
                strrep(list_h5(iter_h5).name,'.mat','.h5')])

            mkdir([dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

            movefile([dir_data '/00_train/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name],...
                [dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

        elseif exist([dir_ref '/00_train_bad/' ...
                list_cls(iter_cls).name '/'...
                strrep(list_h5(iter_h5).name,'.h5','.mat')])

            mkdir([dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

            movefile([dir_data '/00_train/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name],...
                [dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

        elseif exist([dir_ref '/00_train_bad/' ...
                list_cls(iter_cls).name '/'...
                strrep(list_h5(iter_h5).name,'.mat','.png')])

            mkdir([dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

            movefile([dir_data '/00_train/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name],...
                [dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

        elseif exist([dir_ref '/00_train_bad/' ...
                list_cls(iter_cls).name '/'...
                strrep(list_h5(iter_h5).name,'.h5','.png')])

            mkdir([dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])

            movefile([dir_data '/00_train/' ...
                list_cls(iter_cls).name '/'...
                list_h5(iter_h5).name],...
                [dir_data '/00_train_bad/' ...
                list_cls(iter_cls).name])
        end
          
    end

end
